FROM php:8.2-fpm

RUN mkdir portfolio_backend

WORKDIR /var/www/html/portfolio_backend

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libzip-dev \
    libicu-dev \
    && docker-php-ext-configure intl \
    && docker-php-ext-install zip pdo intl

RUN apt-get install -y libcurl4-openssl-dev pkg-config libssl-dev

RUN pecl install mongodb \
    && docker-php-ext-enable mongodb

RUN pecl config-set php_ini /etc/php.ini

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN echo "#!/bin/sh\ncomposer update \ncomposer install\nphp artisan serve --host=0.0.0.0 --port=8000" > /start.sh
RUN chmod +x /start.sh

CMD ["/start.sh"]