FROM node:21-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip

RUN npm install -g pnpm

COPY portfolio_frontend .

RUN pnpm install tsx

RUN pnpm install

CMD ["pnpm", "run", "start_server"]